# Generated by Django 4.2.4 on 2023-09-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_alter_applicant_applicant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='ssn',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='city',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='first_name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='last_name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='state',
            field=models.TextField(max_length=15),
        ),
    ]
