# Generated by Django 4.2.4 on 2023-08-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=30)),
                ('bank_logo', models.CharField(max_length=30)),
                ('subscription', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
    ]
