# Generated by Django 4.2.4 on 2023-08-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bank_logo',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='bank_id',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='bank',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='bank',
            name='logo',
            field=models.ImageField(default='404', upload_to=''),
        ),
    ]
