# Generated by Django 4.2.4 on 2023-08-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_rename_bank_logo_bank_name_remove_bank_bank_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
