# Generated by Django 4.2.4 on 2023-09-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_alter_bank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.TextField(max_length=30),
        ),
    ]
