# Generated by Django 4.2.3 on 2023-07-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(max_length=30)),
                ('loan_requirement', models.TextField(blank=True, null=True)),
                ('apr', models.DecimalField(decimal_places=2, default=2.99, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, default=50000, max_digits=7)),
                ('term', models.IntegerField(default=180, max_length=3)),
                ('dealer_fee', models.DecimalField(decimal_places=3, default=10.99, max_digits=5)),
            ],
        ),
    ]
