# Generated by Django 4.2.3 on 2023-07-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
