# Generated by Django 4.2.4 on 2023-08-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_remove_loan_bank_id_loan_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='bank',
        ),
    ]
