# Generated by Django 4.2.4 on 2023-09-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loan_bank_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='bank_id',
            new_name='bank',
        ),
    ]
