# Generated by Django 4.2.4 on 2023-09-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_alter_bank_name'),
        ('loans', '0008_rename_bank_id_loan_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank'),
        ),
    ]
